#!/bin/bash

# Find the vcf/ped file and convert it to bed format

echo Finding and processing input file...

input="$(ls | egrep -e ".vcf|.vcf.gz|.ped")"

echo $input
if [[ "$input" == *ped ]] 
then
    filename="$(echo $input | cut -f1 -d.)" 
    ./plink --file $filename --recode --out me > run.log
elif [[ "$input" == *vcf ]]
then
    ./plink --vcf $input --maf 0.05 --recode --out me > run.log 2>error.log
elif [[ "$input" == *gz ]]
then
    ./plink --vcf $input --maf 0.05 --recode --out me > run.log 2>error.log
else
    echo No vcf/ped file found in the current directory
    exit 1
fi

# Take the me.ped file 

echo
echo
echo Binary Ancestry Option is 1 
echo Continental Ancestry Option is 2
echo
echo Which ancestry do you want to check

read option

if [ $option = "1" ]; then
    
    ./plink --noweb --bfile reference_panel/yri --merge me.ped me.map --make-bed --out merge

    # Run admixture on the final bed
    # K=2 for binary checking

    ./admixture merge.bed 2 >> run.log 2>>error.log
   
    # Merging the sample with hapmap might scramble its position.
    # Find which row in the final Q file corresponds to the sample

    Rscript plots/plotBinary.R 1>>error.log
    
    echo
    echo Correlations are given below for and against
else
    ./plink --noweb --bfile reference_panel/PAP --merge me.ped me.map --make-bed --out merge1 >> run.log 2>>error.log
    
    ./plink --bfile merge1 -geno 0.999 --make-bed --out merge >> run.log 2>>error.log

    ./admixture -j5 --supervised merge.bed 9 >> run.log 2>>error.log >> run.log 2>>error.log
    Rscript plots/plot.R 1>>error.log

    echo
    echo Correlations are given below
fi

echo
cat ancestry.txt
rm -f merge1.bed merge1.fam merge1.bim merge.bed merge.fam merge.bim
rm -f me.ped me.map me.log
